### ISSUE TITLE
Is it possible to link to directory through markdown on the index.md?

### ISSUE THREAD

**Issue by Lombardi** [b2a3e8/jekyll-theme-console#3]
I don't want to be linking to just one thing on the index.md file and it will be nice to the whole directory like in the post format. I tried and researched different solutions but, I was not able to find the exact answer to this question. If you need me to explain more, I will happily to do so.  

I was wondering if this is possible to be fixed because I really like this theme.

**Comment by b2a3e8** [comment]
I'm not sure if I understand you correctly: You want to include the contents of the posts on the index page instead of only listing hyperlinks to those posts?

**Comment by Lombardi** [comment]
So, if you visit the link I made with your theme, https://lombardi.github.io/Applied-Data-Science-Masters/, you can see that I have made some hyperlinks for what courses I took and I want it so, that when a user clicks on the link, it displays everything in that directory. Does that make sense now?

**Comment by b2a3e8** [comment]
Luckily there are some others who had the same question/problem: https://stackoverflow.com/questions/17677094/jekyll-for-loop-over-all-images-in-a-folder
If that doesnt work out for you, please create an issue in the jekyll repo (https://github.com/jekyll/jekyll) because this is a jekyll related question and not an issue with this theme.
